name: clip_link_repository
description: "a flutter package which provides a repository for Clip Link App."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  spoo_me_api:
    path: ../spoo_me_api
  clip_link_database:
    path: ../clip_link_database

dev_dependencies:
  build_runner: ^2.4.13
  coverage: ^1.10.0
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.7
  flutter_test:
    sdk: flutter