name: clip_link_repository
description: "A dart repository which manages the ClipLink domain."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  spoo_me_api:
    path: ../spoo_me_api

dev_dependencies:
  build_runner: ^2.4.13
  coverage: ^1.10.0
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
