name: flutter_clip_link
description: "Clip Link App is a URl Shortener App that allows you to create
  short links for your favourite websites."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  iconsax_plus: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/illustration/
    - assets/icons/

# To generate the launcher icons for the app, run:
# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path_android: "assets/app_icons/android-icon-1024x1024.png"
  image_path_ios: "assets/app_icons/ios-icon-1024x1024.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/app_icons/adaptive-icon-background-1024x1024.png"
  adaptive_icon_foreground: "assets/app_icons/adaptive-icon-foreground-768x768.png"
  min_sdk_android: 24
  web:
    generate: true
    image_path: "assets/app_icons/android-icon-1024x1024.png"
    background_color: "#4F378B"

flutter_gen:
  output: lib/src/core/res/generated/
  integrations:
    flutter_svg: true
  line_length: 80
