name: flutter_clip_link
description: "Clip Link App is a URl Shortener App that allows you to create
  short links for your favourite websites."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animated_checkmark: ^3.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.2.8
  hydrated_bloc: ^9.1.5 
  iconsax_plus: ^1.0.0
  infinite_scroll_pagination: ^4.0.0
  loader_overlay: ^4.0.2+1
  loggy: ^2.0.3
  path_provider: ^2.1.4
  pull_to_refresh: ^2.0.0
  reactive_forms: ^17.0.1
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/illustration/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700

# To generate the launcher icons for the app, run:
# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path_android: "assets/app_icons/android-icon-1024x1024.png"
  image_path_ios: "assets/app_icons/ios-icon-1024x1024.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/app_icons/adaptive-icon-background-1024x1024.png"
  adaptive_icon_foreground: "assets/app_icons/adaptive-icon-foreground-768x768.png"
  min_sdk_android: 24
  web:
    generate: true
    image_path: "assets/app_icons/android-icon-1024x1024.png"
    background_color: "#4F378B"

# To re-generate the assets, run:
# dart run build_runner build
flutter_gen:
  output: lib/src/core/res/generated/
  integrations:
    flutter_svg: true
  line_length: 80
