name: spoo_me_api
description: "A flutter package for the Spoo.me API client."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
