name: clip_link_local_datasource
description: "A flutter package for Clip Link Local Datasource,
it provides a local databases-related functionality for the Clip Link App."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.26
  sqlite3: ^2.4.7
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  test: ^1.25.7

flutter: