import 'package:flutter/material.dart';

class AppColorScheme {
  ColorScheme get light => ColorScheme.fromSeed(
        seedColor: Colors.deepPurple,
        brightness: Brightness.light,
        primary: const Color(0xff65558F),
        onPrimary: const Color(0xffFFFFFF),
        primaryContainer: const Color(0xffEADDFF),
        onPrimaryContainer: const Color(0xff4F378A),
        secondary: const Color(0xff625B71),
        onSecondary: const Color(0xffFFFFFF),
        secondaryContainer: const Color(0xffE8DEF8),
        onSecondaryContainer: const Color(0xff4A4459),
        tertiary: const Color(0xff4A4459),
        onTertiary: const Color(0xffFFFFFF),
        tertiaryContainer: const Color(0xffFFD8E4),
        onTertiaryContainer: const Color(0xff633B48),
        error: const Color(0xffB3261E),
        onError: const Color(0xffFFFFFF),
        errorContainer: const Color(0xffF9DEDC),
        onErrorContainer: const Color(0xff852221),
        surface: const Color(0xffFEF7FF),
        onSurface: const Color(0xff1D1B20),
        onSurfaceVariant: const Color(0xff49454F),
        surfaceTint: const Color(0xff6750A4),
        outline: const Color(0xff79747E),
        outlineVariant: const Color(0xffCAC4D0),
        shadow: const Color(0xff000000),
        scrim: const Color(0xff000000),
        inverseSurface: const Color(0xff322F35),
        primaryFixed: const Color(0xffEADDFF),
        onPrimaryFixed: const Color(0xff21005D),
        primaryFixedDim: const Color(0xffD0BCFF),
        onPrimaryFixedVariant: const Color(0xff4F378B),
        secondaryFixed: const Color(0xffE8DEF8),
        onSecondaryFixed: const Color(0xff1D192B),
        secondaryFixedDim: const Color(0xffCCC2DC),
        onSecondaryFixedVariant: const Color(0xff4A4458),
        tertiaryFixed: const Color(0xffFFD8E4),
        onTertiaryFixed: const Color(0xff31111D),
        tertiaryFixedDim: const Color(0xffEFB8C8),
        onTertiaryFixedVariant: const Color(0xff633B48),
        surfaceContainer: const Color(0xffF3EDF7),
        surfaceDim: const Color(0xffDED8E1),
        surfaceBright: const Color(0xffFEF7FF),
        surfaceContainerLow: const Color(0xffF7F2FA),
        surfaceContainerLowest: const Color(0xffFFFFFF),
        surfaceContainerHigh: const Color(0xffECE6F0),
        surfaceContainerHighest: const Color(0xffE7E0EC),
        inversePrimary: const Color(0xffD0BCFF),
        onInverseSurface: const Color(0xffF5EFF7),
      );

  ColorScheme get dark => ColorScheme.fromSeed(
        seedColor: Colors.deepPurple,
        brightness: Brightness.dark,
        primary: const Color(0xffD0BCFE),
        onPrimary: const Color(0xff381E72),
        primaryContainer: const Color(0xff4F378B),
        onPrimaryContainer: const Color(0xffEADDFF),
        primaryFixed: const Color(0xffEADDFF),
        onPrimaryFixed: const Color(0xff21005D),
        primaryFixedDim: const Color(0xffD0BCFF),
        onPrimaryFixedVariant: const Color(0xff4F378B),
        secondary: const Color(0xffCCC2DC),
        onSecondary: const Color(0xff332D41),
        secondaryContainer: const Color(0xff4A4458),
        onSecondaryContainer: const Color(0xffE8DEF8),
        secondaryFixed: const Color(0xffE8DEF8),
        onSecondaryFixed: const Color(0xff1D192B),
        secondaryFixedDim: const Color(0xffCCC2DC),
        onSecondaryFixedVariant: const Color(0xff4A4458),
        tertiary: const Color(0xffEFB8C8),
        onTertiary: const Color(0xff492532),
        tertiaryContainer: const Color(0xff633B48),
        onTertiaryContainer: const Color(0xffFFD8E4),
        tertiaryFixed: const Color(0xffFFD8E4),
        onTertiaryFixed: const Color(0xff31111D),
        tertiaryFixedDim: const Color(0xffEFB8C8),
        onTertiaryFixedVariant: const Color(0xff633B48),
        error: const Color(0xffF2B8B5),
        onError: const Color(0xff601410),
        errorContainer: const Color(0xff8C1D18),
        onErrorContainer: const Color(0xffF9DEDC),
        outline: const Color(0xff938F99),
        surface: const Color(0xff141218),
        onSurface: const Color(0xffE6E0E9),
        onSurfaceVariant: const Color(0xffCAC4D0),
        inverseSurface: const Color(0xffE6E0E9),
        onInverseSurface: const Color(0xff322F35),
        inversePrimary: const Color(0xff6750A4),
        shadow: const Color(0xff000000),
        surfaceTint: const Color(0xffD0BCFF),
        outlineVariant: const Color(0xff49454F),
        scrim: const Color(0xff000000),
        surfaceContainerHighest: const Color(0xff36343B),
        surfaceContainerHigh: const Color(0xff2B2930),
        surfaceDim: const Color(0xff141218),
        surfaceContainer: const Color(0xff211F26),
        surfaceContainerLow: const Color(0xff1D1B20),
        surfaceContainerLowest: const Color(0xff0F0D13),
        surfaceBright: const Color(0xff3B383E),
      );
}
