targets:
  $default:
    builders:
      drift_dev:
        options:
          # Required: A name for the database and it's path
          databases:
            clip_link_database: lib/src/database/database.dart