name: clip_link_database
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  path_provider: ^2.1.5
  path: ^1.9.0
  sqlite3: ^2.4.7

dev_dependencies:
  mocktail: ^1.0.4
  drift_dev: ^2.21.2
  test: ^1.25.7
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter